networks:
  kafka_network:
    driver: bridge
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka_network

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka_network

  iv_onboarding:
    build:
      context: ./iv_onboarding
      dockerfile: Dockerfile
    ports:
      - "8090:3001"
    volumes:
      - ./iv_onboarding:/app
    networks:
      - kafka_network
    depends_on: [kafka]

  iv_vehicle_register:
    build:
      context: ./iv_vehicle_register
      dockerfile: Dockerfile
    ports:
      - "8091:3002"
    networks:
      - kafka_network
    volumes:
      - ./iv_vehicle_register:/app
  
  iv_bff:
      build:
        context: ./iv_bff
        dockerfile: Dockerfile
      ports:
        - "8092:3003"
      networks:
        - kafka_network
      depends_on: [kafka]
  iv_frontend:
      build:
        context: ./presentation/iv_frontend
        dockerfile: Dockerfile
      ports:
        - "8093:3000"
      networks:
        - kafka_network
      depends_on: [kafka]
  iv_teams:
      build:
        context: ./iv_teams
        dockerfile: Dockerfile
      networks:
        - kafka_network
      depends_on: [kafka]
