swagger: '2.0'
info:
  description: Swagger file
  version: 1.0.0
  title: Swagger Rest Veículos Infinity Volts
consumes:
  - application/json
produces:
  - application/json
basePath: /
paths:
  /Veiculos:
    get:
      operationId: api.Veiculos.find_all
      tags:
        - Veículos Infinity Volts
      summary: Lista de veículos
      description: Lista de veículos
      responses:
        200:
          description: Sucesso na leitura de veículos
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                Marca:
                  type: string
                Modelo:
                  type: string
                Ano:
                  type: string
                Autonomia:
                  type: string
                timestamp:
                  type: string
    post:
      operationId: api.Veiculos.create
      tags:
        - Adiciona veículos Infinity Volts
      summary: Cria um veículo e adiciona na lista de veículos
      description: Adiciona na lista de veículos
      parameters:
        - name: person
          in: body
          description: Modelo de Veículo
          required: True
          schema:
            type: object
            properties:
              Marca:
                type: string
                description: Marca do carro
              Modelo:
                type: string
                description: Modelo de Veículo
              Ano:
                type: string
                description: Ano de Fabricação
              Autonomia:
                 type: string
                 description: Autonomia do Veículo
      responses:
        201:
          description: Sucesso ao criar
  /Veiculos/{id}:
    get:
      operationId: api.Veiculos.read_one
      tags:
        - Busca por ID do veículos Infinity Volts
      summary: Busca por ID do veículo da lista de veículos
      description: Busca por ID do veículo
      parameters:
        - name: id
          in: path
          description: Id do veículo
          required: true
          type: string
      responses:
        200:
          description: Sucesso na leitura de um veículo
          schema:
            type: object
            properties:
              id:
                type: string
              Marca:
                type: string
              Modelo:
                type: string
              Ano:
                type: string
              Autonomia:
                type: string
              timestamp:
                type: string
    put:
      operationId: api.Veiculos.update
      tags:
        - Alteração de veículos Infinity Volts
      summary: Atualiza um veículo na lista de veículos
      description: Atualiza um veículo na lista
      parameters:
        - name: id
          in: path
          description: Id do veículos
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              Marca:
                type: string
              Modelo:
                type: string
              Ano:
                type: string
              Autonomia:
                type: string
      responses:
        200:
          description: Sucesso ao atualizar
    delete:
      operationId: api.Veiculos.delete
      tags:
        - Deleta veículos Infinity Volts
      summary: Deleta um veículo da lista de carros
      description: Deleta um veículo
      parameters:
        - name: id
          in: path
          description: Id do veículo
          required: true
          type: string
      responses:
        200:
          description: Sucesso ao deletar
  