name: Build and Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Define the Docker service that GitHub Actions will use.
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      # Check out the code from the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional, recommended for multi-architecture builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker Cache (optional)
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      # Build Docker images using Docker Compose
      - name: Build Docker Compose images
        run: docker-compose -f docker-compose.yml build


